import io
import os
import re
import json
import zipfile
import httpx
import tempfile
from datetime import datetime
from typing import List, Dict, Any, Optional, Tuple, Literal
from fpdf import FPDF
from PIL import Image
import markdown as md
import mistune
from jinja2 import Environment, BaseLoader

from statm8.models.export import ExportResponse, ExportStatusResponse, PlotInfo
from statm8.services.storage import (
    upload_export_to_cloudinary,
    save_export_to_db,
    get_vlm_analysis_by_csv,
    get_plots_for_csv,
    get_dataset_summary_from_db,
    get_csv_name_by_id
)


# LaTeX report template using Jinja2
# Uses custom delimiters to avoid conflicts with LaTeX braces:
# - \VAR{...} for variables (instead of {{ ... }})
# - \BLOCK{...} for blocks (instead of {% ... %})
# - \#{...} for comments (instead of {# ... #})
LATEX_TEMPLATE = r"""
\documentclass[11pt,a4paper]{report}

% Packages
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{hyperref}
\usepackage{geometry}
\usepackage{fancyhdr}
\usepackage{xcolor}
\usepackage{listings}
\usepackage{float}

% Page geometry
\geometry{margin=1in}

% Header and footer
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\leftmark}
\fancyhead[R]{\VAR{title | latex_escape}}
\fancyfoot[C]{\thepage}
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0.4pt}

% Hyperref settings
\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    filecolor=magenta,
    urlcolor=cyan,
}

% Code listing style
\lstset{
    basicstyle=\ttfamily\small,
    breaklines=true,
    frame=single,
    backgroundcolor=\color{gray!10},
}

\title{\textbf{\VAR{title | latex_escape}}}
\author{Generated by StatM8}
\date{\VAR{generated_date}}

\begin{document}

\maketitle
\tableofcontents
\newpage

\BLOCK{if summary}
\chapter{Dataset Overview}

\section{Basic Information}
\begin{itemize}
    \item \textbf{Dataset:} \VAR{dataset_name | latex_escape}
    \item \textbf{File Type:} \VAR{summary.file_type | latex_escape}
    \item \textbf{Total Rows:} \VAR{summary.total_rows}
    \item \textbf{Total Columns:} \VAR{summary.total_columns}
\end{itemize}

\BLOCK{if summary.columns_info}
\section{Column Information}

\begin{longtable}{|l|l|r|r|}
\hline
\textbf{Column Name} & \textbf{Data Type} & \textbf{Non-Null Count} & \textbf{Unique Count} \\
\hline
\endfirsthead
\hline
\textbf{Column Name} & \textbf{Data Type} & \textbf{Non-Null Count} & \textbf{Unique Count} \\
\hline
\endhead
\hline
\endfoot
\BLOCK{for col in summary.columns_info}
\VAR{col.name | latex_escape} & \VAR{col.dtype | latex_escape} & \VAR{col.non_null_count} & \VAR{col.unique_count} \\
\hline
\BLOCK{endfor}
\end{longtable}
\BLOCK{endif}

\BLOCK{if summary.ai_summary}
\section{AI-Generated Summary}

\VAR{summary.ai_summary | markdown_to_latex}
\BLOCK{endif}

\BLOCK{endif}

\BLOCK{if plots}
\chapter{Generated Visualizations}

\BLOCK{for plot in plots}
\section{\VAR{plot.filename | latex_escape}}

\BLOCK{if plot.analysis}
\subsection*{Analysis}
\VAR{plot.analysis | markdown_to_latex}

\BLOCK{endif}
\begin{figure}[H]
    \centering
    \includegraphics[width=0.9\textwidth]{\VAR{plot.relative_path}}
    \caption{\VAR{plot.filename | latex_escape}}
\end{figure}

\BLOCK{endfor}
\BLOCK{endif}

\BLOCK{if vlm_summary}
\chapter{VLM Analysis Summary}

\VAR{vlm_summary | markdown_to_latex}
\BLOCK{endif}

\end{document}
"""


def latex_escape(text: Any) -> str:
    """
    Escape special LaTeX characters in text.
    """
    if text is None:
        return ""
    
    text = str(text)
    
    # LaTeX special characters that need escaping
    special_chars = {
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
        '\\': r'\textbackslash{}',
        '<': r'\textless{}',
        '>': r'\textgreater{}',
    }
    
    # First escape backslashes, then other characters
    text = text.replace('\\', r'\textbackslash{}')
    for char, escaped in special_chars.items():
        if char != '\\':  # Skip backslash as it's already handled
            text = text.replace(char, escaped)
    
    return text


class LaTeXRenderer(mistune.BaseRenderer):
    """
    Custom mistune v3 renderer that converts Markdown to LaTeX.
    Produces equivalent visual output to rendered Markdown.
    
    In mistune v3, renderer methods receive (token, state) arguments
    where token is a dict containing the parsed element data.
    """
    NAME = 'latex'
    
    def _escape_text(self, text: str) -> str:
        """Escape LaTeX special characters in plain text."""
        if not text:
            return ""
        
        # LaTeX special characters
        replacements = [
            ('\\', r'\textbackslash{}'),
            ('&', r'\&'),
            ('%', r'\%'),
            ('$', r'\$'),
            ('#', r'\#'),
            ('_', r'\_'),
            ('{', r'\{'),
            ('}', r'\}'),
            ('~', r'\textasciitilde{}'),
            ('^', r'\textasciicircum{}'),
            ('<', r'\textless{}'),
            ('>', r'\textgreater{}'),
        ]
        
        for char, escaped in replacements:
            text = text.replace(char, escaped)
        
        return text
    
    def _render_children(self, token: dict, state) -> str:
        """Recursively render children tokens to get text content."""
        children = token.get('children')
        if children:
            return self.render_tokens(children, state)
        return ''
    
    def text(self, token: dict, state) -> str:
        """Render plain text with LaTeX escaping."""
        raw = token.get('raw', '')
        return self._escape_text(raw)
    
    def emphasis(self, token: dict, state) -> str:
        """Render *italic* text."""
        children_text = self._render_children(token, state)
        return r'\textit{' + children_text + '}'
    
    def strong(self, token: dict, state) -> str:
        """Render **bold** text."""
        children_text = self._render_children(token, state)
        return r'\textbf{' + children_text + '}'
    
    def link(self, token: dict, state) -> str:
        """Render [text](url) links."""
        children_text = self._render_children(token, state)
        url = token.get('attrs', {}).get('url', '')
        escaped_url = self._escape_text(url)
        if children_text:
            return r'\href{' + escaped_url + '}{' + children_text + '}'
        return r'\url{' + escaped_url + '}'
    
    def image(self, token: dict, state) -> str:
        """Render ![alt](url) images."""
        attrs = token.get('attrs', {})
        url = attrs.get('url', '')
        alt = attrs.get('alt', '')
        escaped_url = url.replace('_', r'\_').replace('%', r'\%')
        caption = self._escape_text(alt) if alt else ''
        return (
            r'\begin{figure}[H]' + '\n'
            r'    \centering' + '\n'
            r'    \includegraphics[width=0.8\textwidth]{' + escaped_url + '}' + '\n'
            + (r'    \caption{' + caption + '}\n' if caption else '')
            + r'\end{figure}'
        )
    
    def codespan(self, token: dict, state) -> str:
        """Render `inline code`."""
        raw = token.get('raw', '')
        # Escape only the characters that break \texttt
        escaped = raw.replace('\\', r'\textbackslash{}')
        escaped = escaped.replace('{', r'\{').replace('}', r'\}')
        escaped = escaped.replace('_', r'\_')
        return r'\texttt{' + escaped + '}'
    
    def linebreak(self, token: dict, state) -> str:
        """Render line break."""
        return r'\\' + '\n'
    
    def softbreak(self, token: dict, state) -> str:
        """Render soft break (typically a space or newline)."""
        return '\n'
    
    def paragraph(self, token: dict, state) -> str:
        """Render paragraph."""
        children_text = self._render_children(token, state)
        return children_text + '\n\n'
    
    def heading(self, token: dict, state) -> str:
        """Render # headers at various levels."""
        children_text = self._render_children(token, state)
        level = token.get('attrs', {}).get('level', 1)
        commands = {
            1: r'\section*',
            2: r'\subsection*',
            3: r'\subsubsection*',
            4: r'\paragraph*',
            5: r'\subparagraph*',
            6: r'\subparagraph*',
        }
        cmd = commands.get(level, r'\paragraph*')
        return cmd + '{' + children_text + '}\n\n'
    
    def thematic_break(self, token: dict, state) -> str:
        """Render --- horizontal rules."""
        return r'\noindent\rule{\textwidth}{0.4pt}' + '\n\n'
    
    def block_code(self, token: dict, state) -> str:
        """Render fenced code blocks ```code```."""
        raw = token.get('raw', '')
        attrs = token.get('attrs', {})
        lang = attrs.get('info', '')
        
        if lang:
            return (
                r'\begin{lstlisting}[language=' + lang + ']\n'
                + raw
                + r'\end{lstlisting}' + '\n\n'
            )
        return (
            r'\begin{lstlisting}' + '\n'
            + raw
            + r'\end{lstlisting}' + '\n\n'
        )
    
    def block_quote(self, token: dict, state) -> str:
        """Render > blockquotes."""
        children_text = self._render_children(token, state)
        return (
            r'\begin{quote}' + '\n'
            + children_text
            + r'\end{quote}' + '\n\n'
        )
    
    def list(self, token: dict, state) -> str:
        """Render lists (both ordered and unordered)."""
        children_text = self._render_children(token, state)
        attrs = token.get('attrs', {})
        ordered = attrs.get('ordered', False)
        env = 'enumerate' if ordered else 'itemize'
        return (
            r'\begin{' + env + '}\n'
            + children_text
            + r'\end{' + env + '}\n\n'
        )
    
    def list_item(self, token: dict, state) -> str:
        """Render list items."""
        children_text = self._render_children(token, state)
        # Strip trailing newlines and add proper formatting
        text = children_text.strip()
        return r'    \item ' + text + '\n'
    
    def block_text(self, token: dict, state) -> str:
        """Render block text (used inside list items)."""
        children_text = self._render_children(token, state)
        return children_text
    
    def block_html(self, token: dict, state) -> str:
        """Handle raw HTML blocks - convert to comment or ignore."""
        return '% HTML block omitted\n'
    
    def inline_html(self, token: dict, state) -> str:
        """Handle inline HTML - strip tags."""
        return ''
    
    def newline(self, token: dict, state) -> str:
        """Render newline."""
        return '\n'
    
    def blank_line(self, token: dict, state) -> str:
        """Render blank line."""
        return '\n'


def convert_markdown_to_latex(text: str) -> str:
    """
    Convert Markdown-formatted text to LaTeX.
    Uses mistune with a custom LaTeX renderer to properly convert
    all markdown syntax (bold, italic, headers, lists, etc.) to
    their LaTeX equivalents.
    
    Args:
        text: Markdown-formatted string
        
    Returns:
        LaTeX-formatted string with equivalent visual output
    """
    if not text:
        return ""
    
    # Create markdown parser with LaTeX renderer
    renderer = LaTeXRenderer()
    markdown = mistune.create_markdown(renderer=renderer)
    
    # Convert and return
    result = markdown(text)
    
    # Clean up excessive newlines
    result = re.sub(r'\n{3,}', '\n\n', result)
    
    return result.strip()


def get_latex_environment() -> Environment:
    """
    Create a Jinja2 environment configured for LaTeX template rendering.
    Uses custom delimiters to avoid conflicts with LaTeX braces.
    """
    env = Environment(
        loader=BaseLoader(),
        block_start_string=r'\BLOCK{',
        block_end_string='}',
        variable_start_string=r'\VAR{',
        variable_end_string='}',
        comment_start_string=r'\#{',
        comment_end_string='}',
    )
    env.filters['latex_escape'] = latex_escape
    env.filters['markdown_to_latex'] = convert_markdown_to_latex
    return env


def convert_markdown_to_html(text: str) -> str:
    """
    Convert markdown text to HTML for PDF rendering.
    Uses the markdown library with extensions for tables, fenced code, and newlines.
    """
    if not text:
        return text
    
    # Convert markdown to HTML with useful extensions
    html = md.markdown(
        text,
        extensions=['tables', 'fenced_code', 'nl2br', 'sane_lists']
    )
    
    # fpdf2's write_html has limited <pre>/<code> support
    # Replace <code> with monospace font tags for better rendering
    html = html.replace('<code>', '<font face="Courier" size="9">')
    html = html.replace('</code>', '</font>')
    
    # Handle <pre> blocks (from fenced code blocks)
    html = html.replace('<pre>', '<font face="Courier" size="9">')
    html = html.replace('</pre>', '</font><br>')
    
    return html


class EDAReportPDF(FPDF):
    """Custom PDF class for EDA reports"""
    
    def __init__(self, title: str = "EDA Report"):
        super().__init__()
        self.report_title = title
        self.set_auto_page_break(auto=True, margin=15)
        
    def header(self):
        self.set_font('Helvetica', 'B', 12)
        self.cell(0, 10, self.report_title, 0, 1, 'C')
        self.ln(5)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}}', 0, 0, 'C')
        
    def chapter_title(self, title: str):
        self.set_font('Helvetica', 'B', 14)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 10, title, 0, 1, 'L', fill=True)
        self.ln(4)
        
    def chapter_body(self, text: str, render_markdown: bool = True):
        self.set_font('Helvetica', '', 10)
        
        if render_markdown and text:
            # Convert markdown to HTML and render with write_html
            html = convert_markdown_to_html(text)
            self.write_html(html)
        else:
            # Fallback to plain text rendering
            text = text.encode('latin-1', 'replace').decode('latin-1')
            self.multi_cell(0, 5, text)
        
        self.ln()
        
    def add_plot(self, image_path: str, caption: str = ""):
        """Add a plot image to the PDF"""
        if not os.path.exists(image_path):
            return
            
        try:
            # Get image dimensions to scale properly
            with Image.open(image_path) as img:
                img_width, img_height = img.size
            
            # Calculate scaling to fit page width (max 180mm)
            max_width = 180
            max_height = 120
            
            aspect_ratio = img_width / img_height
            
            if aspect_ratio > max_width / max_height:
                # Width limited
                pdf_width = max_width
                pdf_height = max_width / aspect_ratio
            else:
                # Height limited
                pdf_height = max_height
                pdf_width = max_height * aspect_ratio
            
            # Check if we need a new page
            if self.get_y() + pdf_height + 20 > self.h - 20:
                self.add_page()
            
            # Center the image
            x_pos = (self.w - pdf_width) / 2
            self.image(image_path, x=x_pos, w=pdf_width)
            
            if caption:
                self.set_font('Helvetica', 'I', 9)
                caption = caption.encode('latin-1', 'replace').decode('latin-1')
                self.cell(0, 10, caption, 0, 1, 'C')
            
            self.ln(5)
            
        except Exception as e:
            self.chapter_body(f"[Error loading image: {str(e)}]")


def check_export_status(csv_id: str, uid: Optional[str] = None) -> ExportStatusResponse:
    """Check what data is available for export from MongoDB"""
    # Get csv_name for display
    csv_name = get_csv_name_by_id(csv_id)
    
    # Get CSV document to check for summary
    summary = get_dataset_summary_from_db(csv_id)
    has_summary = summary is not None
    
    # Get plots from MongoDB
    plots = get_plots_for_csv(csv_id, uid)
    has_plots = len(plots) > 0
    plot_count = len(plots)
    
    # Check for VLM analysis
    vlm_analysis = get_vlm_analysis_by_csv(csv_id)
    has_vlm = vlm_analysis is not None
    
    return ExportStatusResponse(
        csv_id=csv_id,
        csv_name=csv_name,
        has_summary=has_summary,
        has_plots=has_plots,
        plot_count=plot_count,
        has_vlm_analysis=has_vlm,
        can_export=has_summary or has_plots
    )


def load_dataset_summary_from_db(csv_id: str) -> Optional[Dict[str, Any]]:
    """Load dataset summary from MongoDB by csv_id"""
    summary = get_dataset_summary_from_db(csv_id)
    return summary


def load_vlm_analysis_from_db(csv_id: str) -> Optional[Dict[str, Any]]:
    """Load VLM analysis from MongoDB by csv_id"""
    return get_vlm_analysis_by_csv(csv_id)


def get_plots_from_db(csv_id: str, uid: Optional[str] = None) -> List[PlotInfo]:
    """Get list of plots from MongoDB by csv_id"""
    plots = get_plots_for_csv(csv_id, uid)
    return [
        PlotInfo(
            filename=p["filename"],
            url=p["cloudinary_url"]
        )
        for p in plots
    ]


async def fetch_image_bytes(url: str) -> bytes:
    """Fetch image bytes from URL"""
    async with httpx.AsyncClient() as client:
        response = await client.get(url)
        response.raise_for_status()
        return response.content


def create_export_zip_in_memory(
    report_content: bytes,
    report_filename: str,
    plot_images: List[Tuple[str, bytes]],
    dataset_name: str
) -> bytes:
    """
    Create a ZIP file in memory containing the report and associated images.
    
    Args:
        report_content: Bytes of the report file
        report_filename: Name for the report file in the zip
        plot_images: List of (filename, bytes) tuples for images
        dataset_name: Name of the dataset
    
    Returns:
        Bytes of the ZIP file
    """
    zip_buffer = io.BytesIO()
    
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zf:
        # Add the main report file at root level
        zf.writestr(report_filename, report_content)
        
        # Add images to images/{dataset_name}/ subfolder
        for filename, image_bytes in plot_images:
            zf.writestr(f"images/{dataset_name}/{filename}", image_bytes)
    
    return zip_buffer.getvalue()


async def generate_pdf_report_with_upload(
    uid: str,
    csv_id: str,
    vlm_analysis_id: Optional[str] = None,
    include_summary: bool = True,
    include_plots: bool = True,
    include_vlm_analysis: bool = False,
    include_code: bool = False,
    custom_title: Optional[str] = None
) -> ExportResponse:
    """
    Generate a PDF report in memory and upload to Cloudinary.
    
    Args:
        uid: User ID for storage
        csv_id: CSV file ID (MongoDB ObjectId string)
        vlm_analysis_id: VLM analysis ID (required if include_vlm_analysis=True)
        include_summary: Include dataset summary section
        include_plots: Include generated plots
        include_vlm_analysis: Include VLM plot analyses
        include_code: Include generated code blocks
        custom_title: Custom title for the report
    
    Returns:
        ExportResponse with Cloudinary download URL
    """
    # Get csv_name for display
    csv_name = get_csv_name_by_id(csv_id)
    
    # Generate PDF filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    pdf_filename = f"{csv_name}_eda_report_{timestamp}.pdf"
    
    # Create PDF
    title = custom_title or f"EDA Report: {csv_name}"
    pdf = EDAReportPDF(title=title)
    pdf.alias_nb_pages()
    pdf.add_page()
    
    sections_included = []
    total_plots = 0
    
    # Title page info
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 10, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1, 'C')
    pdf.cell(0, 10, f"Dataset: {csv_name}", 0, 1, 'C')
    pdf.ln(10)
    
    # Dataset Summary Section
    if include_summary:
        summary_data = load_dataset_summary_from_db(csv_id)
        if summary_data:
            sections_included.append("summary")
            
            pdf.chapter_title("Dataset Overview")
            
            # Basic info
            overview_text = f"""
File Type: {summary_data.get('file_type', 'N/A')}
Total Rows: {summary_data.get('total_rows', 'N/A')}
Total Columns: {summary_data.get('total_columns', 'N/A')}
            """.strip()
            pdf.chapter_body(overview_text, False)
            
            # Column information
            if 'columns_info' in summary_data:
                pdf.chapter_title("Column Information")
                for col in summary_data['columns_info']:
                    col_text = f"- {col.get('name', 'N/A')}: {col.get('dtype', 'N/A')} ({col.get('non_null_count', 'N/A')} non-null)"
                    pdf.chapter_body(col_text)
            
            # AI Summary
            if 'ai_summary' in summary_data and summary_data['ai_summary']:
                pdf.chapter_title("AI-Generated Summary")
                pdf.chapter_body(summary_data['ai_summary'])
    
    # Plots Section
    if include_plots:
        plots = get_plots_from_db(csv_id, uid)
        if plots:
            sections_included.append("plots")
            total_plots = len(plots)
            
            pdf.add_page()
            pdf.chapter_title("Generated Visualizations")
            
            # Load VLM analysis if available and requested
            vlm_data = None
            if include_vlm_analysis:
                vlm_data = load_vlm_analysis_from_db(csv_id)
                if vlm_data:
                    sections_included.append("vlm_analysis")
            
            for idx, plot in enumerate(plots):
                # Add a new page if not the first plot
                if idx > 0:
                    pdf.add_page()
                    
                # Add VLM analysis if available
                if vlm_data and 'plot_analyses' in vlm_data:
                    for analysis in vlm_data['plot_analyses']:
                        if analysis.get('plot_filename') == plot.filename:
                            if analysis.get('analysis'):
                                pdf.set_font('Helvetica', 'I', 9)
                                pdf.chapter_body(analysis['analysis'])
                            break
                
                # Fetch image from Cloudinary and add to PDF
                try:
                    image_bytes = await fetch_image_bytes(plot.url)
                    # Save to temp file for FPDF (FPDF needs a file path)
                    with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as tmp:
                        tmp.write(image_bytes)
                        tmp_path = tmp.name
                    
                    pdf.add_plot(tmp_path, caption=plot.filename)
                    
                    # Clean up temp file
                    os.unlink(tmp_path)
                except Exception as e:
                    pdf.chapter_body(f"[Error loading plot: {plot.filename}]")
            
            # Add VLM summary if available
            if vlm_data and 'summary' in vlm_data and vlm_data['summary']:
                pdf.add_page()
                pdf.chapter_title("VLM Analysis Summary")
                pdf.chapter_body(vlm_data['summary'])
    
    # Generate PDF in memory
    pdf_bytes = bytes(pdf.output())
    file_size = len(pdf_bytes)
    
    # Upload to Cloudinary
    upload_result = await upload_export_to_cloudinary(
        file_bytes=pdf_bytes,
        filename=pdf_filename,
        csv_id=csv_id,
        export_format="pdf"
    )
    
    # Save to MongoDB
    db_result = await save_export_to_db(
        uid=uid,
        csv_id=csv_id,
        vlm_analysis_id=vlm_analysis_id or "",
        export_format="pdf",
        cloudinary_url=upload_result.get("cloudinary_url"),
        public_id=upload_result.get("public_id"),
        file_size_bytes=file_size,
        sections_included=sections_included,
        total_plots=total_plots
    )
    
    return ExportResponse(
        csv_id=csv_id,
        csv_name=csv_name,
        file_size_bytes=file_size,
        sections_included=sections_included,
        total_plots=total_plots,
        generated_at=datetime.now().isoformat(),
        status="success",
        download_url=db_result.get("download_url"),
        export_id=db_result.get("export_id"),
        format="pdf",
        is_zip=False
    )


async def generate_markdown_report_with_upload(
    uid: str,
    csv_id: str,
    vlm_analysis_id: Optional[str] = None,
    include_summary: bool = True,
    include_plots: bool = True,
    include_vlm_analysis: bool = False,
    include_code: bool = False,
    custom_title: Optional[str] = None
) -> ExportResponse:
    """
    Generate a Markdown report in memory, bundle with images into a ZIP, and upload to Cloudinary.
    
    Args:
        uid: User ID for storage
        csv_id: CSV file ID (MongoDB ObjectId string)
        vlm_analysis_id: VLM analysis ID (required if include_vlm_analysis=True)
        include_summary: Include dataset summary section
        include_plots: Include generated plots
        include_vlm_analysis: Include VLM plot analyses
        include_code: Include generated code blocks
        custom_title: Custom title for the report
    
    Returns:
        ExportResponse with Cloudinary download URL for the ZIP file
    """
    # Get csv_name for display
    csv_name = get_csv_name_by_id(csv_id)
    
    # Generate Markdown filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    md_filename = f"{csv_name}_eda_report_{timestamp}.md"
    zip_filename = f"{csv_name}_eda_report_{timestamp}.zip"
    
    sections_included = []
    total_plots = 0
    
    # Build markdown content
    lines = []
    
    # Title
    title = custom_title or f"EDA Report: {csv_name}"
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"**Dataset:** {csv_name}")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    # Dataset Summary Section
    if include_summary:
        summary_data = load_dataset_summary_from_db(csv_id)
        if summary_data:
            sections_included.append("summary")
            
            lines.append("## Dataset Overview")
            lines.append("")
            lines.append(f"- **File Type:** {summary_data.get('file_type', 'N/A')}")
            lines.append(f"- **Total Rows:** {summary_data.get('total_rows', 'N/A')}")
            lines.append(f"- **Total Columns:** {summary_data.get('total_columns', 'N/A')}")
            lines.append("")
            
            # Column information as a table
            if 'columns_info' in summary_data and summary_data['columns_info']:
                lines.append("## Column Information")
                lines.append("")
                lines.append("| Column Name | Data Type | Non-Null Count | Unique Count |")
                lines.append("|-------------|-----------|----------------|--------------|")
                
                for col in summary_data['columns_info']:
                    name = col.get('name', 'N/A')
                    dtype = col.get('dtype', 'N/A')
                    non_null = col.get('non_null_count', 'N/A')
                    unique = col.get('unique_count', 'N/A')
                    lines.append(f"| {name} | {dtype} | {non_null} | {unique} |")
                
                lines.append("")
            
            # AI Summary - preserve original markdown formatting
            if 'ai_summary' in summary_data and summary_data['ai_summary']:
                lines.append("## AI-Generated Summary")
                lines.append("")
                lines.append(summary_data['ai_summary'])
                lines.append("")
    
    # Plots Section - collect images for ZIP
    plot_images: List[Tuple[str, bytes]] = []
    
    if include_plots:
        plots = get_plots_from_db(csv_id, uid)
        if plots:
            sections_included.append("plots")
            total_plots = len(plots)
            
            lines.append("---")
            lines.append("")
            lines.append("## Generated Visualizations")
            lines.append("")
            
            # Load VLM analysis if available and requested
            vlm_data = None
            if include_vlm_analysis:
                vlm_data = load_vlm_analysis_from_db(csv_id)
                if vlm_data:
                    sections_included.append("vlm_analysis")
            
            for plot in plots:
                # Add VLM analysis if available - preserve original markdown
                if vlm_data and 'plot_analyses' in vlm_data:
                    for analysis in vlm_data['plot_analyses']:
                        if analysis.get('plot_filename') == plot.filename:
                            if analysis.get('analysis'):
                                lines.append(analysis['analysis'])
                            break
                
                # Fetch plot image from Cloudinary
                try:
                    image_bytes = await fetch_image_bytes(plot.url)
                    plot_images.append((plot.filename, image_bytes))
                except Exception as e:
                    pass  # Skip failed images
                
                # Add plot image reference - use images/{csv_name}/ subfolder
                lines.append(f"### {plot.filename}")
                lines.append("")
                lines.append(f"![{plot.filename}](images/{csv_name}/{plot.filename})")
                lines.append("")
            
            # Add VLM summary if available - preserve original markdown
            if vlm_data and 'summary' in vlm_data and vlm_data['summary']:
                lines.append("---")
                lines.append("")
                lines.append("## VLM Analysis Summary")
                lines.append("")
                lines.append(vlm_data['summary'])
                lines.append("")
    
    # Build markdown content
    md_content = '\n'.join(lines)
    md_bytes = md_content.encode('utf-8')
    
    # Create ZIP file in memory
    zip_bytes = create_export_zip_in_memory(
        report_content=md_bytes,
        report_filename=md_filename,
        plot_images=plot_images,
        dataset_name=csv_name
    )
    
    file_size = len(zip_bytes)
    
    # Upload ZIP to Cloudinary
    upload_result = await upload_export_to_cloudinary(
        file_bytes=zip_bytes,
        filename=zip_filename,
        csv_id=csv_id,
        export_format="markdown"
    )
    
    # Save to MongoDB
    db_result = await save_export_to_db(
        uid=uid,
        csv_id=csv_id,
        vlm_analysis_id=vlm_analysis_id or "",
        export_format="markdown",
        cloudinary_url=upload_result.get("cloudinary_url"),
        public_id=upload_result.get("public_id"),
        file_size_bytes=file_size,
        sections_included=sections_included,
        total_plots=total_plots
    )
    
    return ExportResponse(
        csv_id=csv_id,
        csv_name=csv_name,
        file_size_bytes=file_size,
        sections_included=sections_included,
        total_plots=total_plots,
        generated_at=datetime.now().isoformat(),
        status="success",
        download_url=db_result.get("download_url"),
        export_id=db_result.get("export_id"),
        format="markdown",
        is_zip=True
    )


async def generate_latex_report_with_upload(
    uid: str,
    csv_id: str,
    vlm_analysis_id: Optional[str] = None,
    include_summary: bool = True,
    include_plots: bool = True,
    include_vlm_analysis: bool = False,
    include_code: bool = False,
    custom_title: Optional[str] = None
) -> ExportResponse:
    """
    Generate a LaTeX report in memory, bundle with images into a ZIP, and upload to Cloudinary.
    Uses Jinja2 templating with the report document class.
    
    Args:
        uid: User ID for storage
        csv_id: CSV file ID (MongoDB ObjectId string)
        vlm_analysis_id: VLM analysis ID (required if include_vlm_analysis=True)
        include_summary: Include dataset summary section
        include_plots: Include generated plots
        include_vlm_analysis: Include VLM plot analyses
        include_code: Include generated code blocks
        custom_title: Custom title for the report
    
    Returns:
        ExportResponse with Cloudinary download URL for the ZIP file
    """
    # Get csv_name for display
    csv_name = get_csv_name_by_id(csv_id)
    
    # Generate LaTeX filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    tex_filename = f"{csv_name}_eda_report_{timestamp}.tex"
    zip_filename = f"{csv_name}_eda_report_{timestamp}.zip"
    
    sections_included = []
    total_plots = 0
    
    # Prepare template data
    template_data = {
        "title": custom_title or f"EDA Report: {csv_name}",
        "dataset_name": csv_name,
        "generated_date": datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        "summary": None,
        "plots": [],
        "vlm_summary": None
    }
    
    # Dataset Summary Section
    if include_summary:
        summary_data = load_dataset_summary_from_db(csv_id)
        if summary_data:
            sections_included.append("summary")
            template_data["summary"] = {
                "file_type": summary_data.get('file_type', 'N/A'),
                "total_rows": summary_data.get('total_rows', 'N/A'),
                "total_columns": summary_data.get('total_columns', 'N/A'),
                "columns_info": summary_data.get('columns_info', []),
                "ai_summary": summary_data.get('ai_summary', '')
            }
    
    # Plots Section - collect images for ZIP
    plot_images: List[Tuple[str, bytes]] = []
    
    if include_plots:
        plots = get_plots_from_db(csv_id, uid)
        if plots:
            sections_included.append("plots")
            total_plots = len(plots)
            
            # Load VLM analysis if available and requested
            vlm_data = None
            if include_vlm_analysis:
                vlm_data = load_vlm_analysis_from_db(csv_id)
                if vlm_data:
                    sections_included.append("vlm_analysis")
            
            for plot in plots:
                # Fetch plot image from Cloudinary
                try:
                    image_bytes = await fetch_image_bytes(plot.url)
                    plot_images.append((plot.filename, image_bytes))
                except Exception as e:
                    pass  # Skip failed images
                
                plot_info = {
                    "filename": plot.filename,
                    "relative_path": f"images/{csv_name}/{plot.filename}",  # Use images/{csv_name}/ subfolder
                    "analysis": None
                }
                
                # Add VLM analysis if available
                if vlm_data and 'plot_analyses' in vlm_data:
                    for analysis in vlm_data['plot_analyses']:
                        if analysis.get('plot_filename') == plot.filename:
                            plot_info["analysis"] = analysis.get('analysis', '')
                            break
                
                template_data["plots"].append(plot_info)
            
            # Add VLM summary if available
            if vlm_data and 'summary' in vlm_data and vlm_data['summary']:
                template_data["vlm_summary"] = vlm_data['summary']
    
    # Render LaTeX template using Jinja2
    env = get_latex_environment()
    template = env.from_string(LATEX_TEMPLATE)
    latex_content = template.render(**template_data)
    
    # Convert to bytes
    tex_bytes = latex_content.encode('utf-8')
    
    # Create ZIP file in memory
    zip_bytes = create_export_zip_in_memory(
        report_content=tex_bytes,
        report_filename=tex_filename,
        plot_images=plot_images,
        dataset_name=csv_name
    )
    
    file_size = len(zip_bytes)
    
    # Upload ZIP to Cloudinary
    upload_result = await upload_export_to_cloudinary(
        file_bytes=zip_bytes,
        filename=zip_filename,
        csv_id=csv_id,
        export_format="latex"
    )
    
    # Save to MongoDB
    db_result = await save_export_to_db(
        uid=uid,
        csv_id=csv_id,
        vlm_analysis_id=vlm_analysis_id or "",
        export_format="latex",
        cloudinary_url=upload_result.get("cloudinary_url"),
        public_id=upload_result.get("public_id"),
        file_size_bytes=file_size,
        sections_included=sections_included,
        total_plots=total_plots
    )
    
    return ExportResponse(
        csv_id=csv_id,
        csv_name=csv_name,
        file_size_bytes=file_size,
        sections_included=sections_included,
        total_plots=total_plots,
        generated_at=datetime.now().isoformat(),
        status="success",
        download_url=db_result.get("download_url"),
        export_id=db_result.get("export_id"),
        format="latex",
        is_zip=True
    )
